#------------[RandomTP]------------#
# A random teleportation addition for GriefPrevention

# Specifically, on the first time the player joins a world, teleport them
# somewhere unclaimed.

# This plugin requires GreifPrevention
# http://dev.bukkit.org/bukkit-plugins/grief-prevention/

# Developed by 10becja
# Check us out at play.minecraft.dk
#----------------------------------#


# Specify a border to teleport within. This is helpful if the server
# uses something like WorldBorder. Set to -1 to ignore
# NOTE: this assumes the Border was set from the worlds spawn location
Border: -1

# The Spawn point to check from. Set to "reset" to have the plugin use the world's spawn
Spawn: reset
 
# World to check for first join (prevents random teleportation first time in nether/end, or other worlds)
World: someworldnamethatwontexist  

# Set bed spawn location on TP
Bed: true

# If your server supports the /sethome command, you can set this to true to force the player to /sethome 
# after they are tp'd (usefule for one time random tp's)
Sethome: true